### ISSUE TITLE
Building and Installing liblpm

### ISSUE THREAD

**Issue by tinajohnson** [rmind/liblpm#8] opened 2019-04-29 20:39 UTC
I am trying to run the lua example that's given in the github page of liblpm (https://github.com/rmind/liblpm#lua-example).

The steps I have taken to build and install are the following in the order given below:

1. make lib LIBDIR=lib
2. make lua LIBDIR=lib/lua/5.1
3. make install DESTDIR=/home/tina/liblpm/src LIBDIR=lib INCDIR=include
4. make lua_install DESTDIR=/home/tina/liblpm/src LIBDIR=lib/lua/5.1

Is this the right way to build and install the library? My end goal is to use liblpm in a project I am working on which uses [Flowscope](https://github.com/emmericp/FlowScope).

Appreciate your help.

**Comment by rmind** [comment] 2019-04-29 21:02
@tinajohnson: Generally yes, if that is your setup. It is really up to you how do you want to use it. Makefile will assume the availability of libtool and pkg-config with settings for Lua. You can also look into the `pkg` directory to see how the RPM and Debian packages are built. Alternatively, you can just build and use one of these packages.

**Comment by tinajohnson** [comment] 2019-04-30 07:31
@rmind I have a Ubuntu 16.04 machine.  After I did `make deb`, I got 3 .deb packages:

1. liblpm1_0.2.1_amd64.deb
2. liblpm1-dbg_0.2.1_amd64.deb
3. liblpm-dev_0.2.1_amd64.deb

I installed them using dpkg. But when I run the lua program as `lua test.lua`, I get the following error:
lua5.1: test.lua:1: module 'lpm' not found:
	no field package.preload['lpm']
	no file './lpm.lua'
	no file '/usr/local/share/lua/5.1/lpm.lua'
	no file '/usr/local/share/lua/5.1/lpm/init.lua'
	no file '/usr/local/lib/lua/5.1/lpm.lua'
	no file '/usr/local/lib/lua/5.1/lpm/init.lua'
	no file '/usr/share/lua/5.1/lpm.lua'
	no file '/usr/share/lua/5.1/lpm/init.lua'
	no file './lpm.so'
	no file '/usr/local/lib/lua/5.1/lpm.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lpm.so'
	no file '/usr/lib/lua/5.1/lpm.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

I ran a system wide search for lpm.so or lpm.lua, but couldn't find one. Apologies if I am missing something very obvious, I am fairly new to lua.

Thank you!

**Comment by tinajohnson** [comment] 2019-04-30 21:46
I tried to make and install commands for lua but I get the following errors:

lua5.1: error loading module 'lpm' from file './lpm.so':
	./lpm.so: undefined symbol: lpm_create

This was with lpm.so in the same folder as the lua file I ran. Could you tell me what I might be missing here?

**Comment by rmind** [comment] 2019-05-01 22:58
@tinajohnson:

- Regarding "undefined symbol: lpm_create" -- you need to **link** the `liblpm` library (lpm.so depends on liblpm.so) and ensure that the library is in the known (or specified) path.  You probably missed the latter, since you compile using a custom relative path.  Alternatively, you can just install the `liblpm1` package which you successfully managed to compile and then link as normal (just `-llpm` flag).

- There was no Debian package for Lua bindings. Anyway, I just committed the changes to add `liblpm-lua`, so `make deb` will now produce it. For now it assumes the Lua 5.1 version.  Tested on Debian 9, but it will most likely just work on Ubuntu.

**Comment by tinajohnson** [comment] 2019-05-02 01:24
Thank you for the commit.

When I try to do make deb now, I get the following error:
libtool: warning: remember to run 'libtool --finish /usr/lib/x86_64-linux-gnu'
libtool --mode=finish /usr/lib/x86_64-linux-gnu/lua/5.1
libtool:   error: invalid argument '/usr/lib/x86_64-linux-gnu/lua/5.1'
Makefile:80: recipe for target 'install' failed
make[3]: *** [install] Error 1
make[3]: Leaving directory '/home/tina/liblpm/pkg/SOURCES'

I am confused about the linking you have mentioned. Right now I am running the lua file as `lua5.1 test.lu`. Do you mean I have to do `lua5.1 -l liblpm test.lua` instead?

Appreciate your time and help.

**Comment by rmind** [comment] 2019-05-02 08:10
@tinajohnson: Ugh, Debian packages are annoying (it's calling install target twice, with `lua_install` too).  I don't have time to fix this properly right now, but before running `make deb` (make sure you clean before), just run `mkdir -p /usr/lib/x86_64-linux-gnu/lua/5.1` fow now.

**Comment by tinajohnson** [comment] 2019-05-02 12:31
@rmind Thank you. Can you tell me about the linking you were talking about? I don't have any C files just a .lua file with this example(https://github.com/rmind/liblpm#lua-example). And I am trying to run the file like this: `lua5.1 test.lua`

**Comment by rmind** [comment] 2019-05-02 13:16
I was talking about the fact that `lpm.so` (Lua bindings library) depends on `liblpm` (the actual library), so the former needs to be linked with the latter (or your application), if you build it yourself, in a custom way.

If you use and the DEB packages, then there is nothing else to do. You use `require("lpm")`, like in the example, and it should just work.

**Comment by rmind** [comment] 2019-05-03 20:43
`liblpm-lua` Debian package has been added (+ an automatic build on Travis); issue resolved.

**Closed as completed by rmind** 2019-05-03 20:43 UTC

**Comment by tinajohnson** [comment] 2019-05-05 13:44
Hi,
I was able to successfully install both liblpm and liblpm-lua and they are installed in paths as shown in the screenshot below. I am trying to run the file like this: `lua5.1 test.lua`. You can also see the error in the screenshot. Any ideas as to why I am still getting the error?

![Screenshot from 2019-05-04 16-12-55](https://user-images.githubusercontent.com/4279549/57194896-8b104980-6f09-11e9-8e3f-ab1611eedaa6.png)

Appreciate your time and help.

**Comment by rmind** [comment] 2019-05-05 15:27
@tinajohnson: That's a bit odd.  Ubuntu might have some differences, since I cannot reproduce your problem on Debian 10:
```
$ uname -srv
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12)
$ dpkg -L liblpm1
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/liblpm.so.1.0.0
/usr/share
/usr/share/doc
/usr/share/doc/liblpm1
/usr/share/doc/liblpm1/changelog.gz
/usr/lib/x86_64-linux-gnu/liblpm.so.1
$ dpkg -L liblpm-lua
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/lua
/usr/lib/x86_64-linux-gnu/lua/5.1
/usr/lib/x86_64-linux-gnu/lua/5.1/lpm.so
/usr/share
/usr/share/doc
/usr/share/doc/liblpm-lua
/usr/share/doc/liblpm-lua/changelog.gz
$ lua ./t_lpm.lua
ok
```

- Can you show me the output of `ldd /usr/lib/x86_64-linux-gnu/lua/5.1/lpm.so`?
- Can you check whether you have `liblpm.so` and `liblpm.so.1` in  `/usr/lib/x86_64-linux-gnu/` which are symlinks to `liblpm.so.1.0.0`?

Thanks.
