### ISSUE TITLE
Lookup returns null random runs

### ISSUE THREAD

**Issue by simPod** [rmind/liblpm#12] opened 2019-05-07 11:06 UTC
I use java bindings.

When running the script all `insert()` pass but when running `lookup()`, on some runs `lookup()` returns null. Any idea why? The code is the same but it randomly works. I'll post PR with test soon.

**Comment by simPod** [comment] 2019-05-07 14:37
I'm not able to make Java tests work in travis here :/

Are you able to execute this several times? Throws `Exception in thread "main" java.lang.AssertionError: Assertion failed: null != 185.102.219.0/24` from time to time.

[bgptable.txt](https://github.com/rmind/liblpm/files/3153137/bgptable.txt)

```java
import org.apache.commons.io.IOUtils;
import org.netbsd.liblpm.LPM;

import java.io.IOException;
import java.io.InputStream;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.nio.charset.Charset;

public class LPMTest {
    public static void main(String[] args) throws UnknownHostException {
        basicTest();
    }

    private static void basicTest() throws UnknownHostException {
        String bgpTable;
        try {
            InputStream in = LPMTest.class.getClassLoader().getResourceAsStream("bgptable.txt");
            bgpTable = IOUtils.toString(in, Charset.defaultCharset());
        } catch (IOException e) {
            throw new RuntimeException("Failed fetching BGP table", e);
        }
        if (bgpTable.length() == 0) {
            throw new RuntimeException("BGP table is empty");
        }
        String[] bgpEntries = bgpTable.split("[\\r\\n]+");

        LPM<String> lpm = new LPM<>();

        for (String bgpEntry : bgpEntries) {
            String[] split = bgpEntry.split(" ");
            try {
                String prefix = split[0];
                assertEqual(lpm.insert(prefix, prefix), true);
            } catch (ArrayIndexOutOfBoundsException e) {
                // Empty line
            }
        }

        assertEqual(lpm.lookup(InetAddress.getByName("185.102.219.225").getAddress()), "185.102.219.0/24");
    }

    private static void assertEqual(Object a, Object b) {
        if ((a == null && b != null) || (a != null && !a.equals(b))) {
            throw new AssertionError(
                "Assertion failed: " + a + " != " + b);
        }
    }
}
```

**Comment by rmind** [comment] 2019-05-07 21:30
Given that the `liblpm` library itself is extensively tested by now, I suspect the problem might be with the Java bindings.  Just to rule out something being weird with your data, I ran an equivalent test from C and Lua.  No problem after a few thousand runs.  Lua code:
```lua
local lpm = require("lpm")

for i = 1, 1000 do
  local acl = lpm.new()
  -- cut -f1 -d' ' bgptable.txt > bgptable1.txt
  for line in io.lines("bgptable1.txt") do
    local addr, preflen = lpm.tobin(line)
    if not acl:insert(addr, preflen, line) then
      os.exit(1)
    end
  end
  local ret = acl:lookup(lpm.tobin("185.102.219.225"))
  assert(ret == "185.102.219.0/24")
  print(i)
end
```
I don't use/code Java (or Java liblpm bindings); however, there is one company which is using it.

@SingularityCat: Elliot -- would you perhaps like to have a look?

**Comment by simPod** [comment] 2019-05-10 08:14
@rmind thanks for taking a look! When I do the same in java (run the test 1000x in _for_ cycle) it yields different results so the behaviour is indeed inconstent between calls (previously I though it needed to be relaunched).

**Comment by SingularityCat** [comment] 2019-05-14 22:45
Hello @rmind! For our Java projects, we actually ended up using a pure Java implementation of the same algorithm, although I can't exactly remember why (@moshisushi may or may not remember).

Regarding the liblpm JNI bindings, I tried compiling them, but it seems Java has marched on - `javah` is considered deprecated, and wasn't in my current installation...

Anyway, I fixed that (use `javac -h <dir> ...`), and was able to reproduce this behaviour.
I know next to nothing about JNI, so it may take me a while to figure out what's going on here.

So far, I've had a crack at running it in Valgrind, but I seem to get a _lot_ of false positives.

**Comment by pgc-13** [comment] 2019-05-15 08:44
@SingularityCat Yeah it's been a while so I'm not sure that I remember the specific reason, but iirc the plain java version was implemented in parallel or before the JNI bindings, and performed well enough (also there were some uncertainties around JNI and memory mgmt I think). However I don't recall random nulls being an issue. There is a unit test for the bindings that used to pass consistently... would be interesting to know if that's still the case.

**Comment by rmind** [comment] 2019-05-16 21:33
@SingularityCat @moshisushi @simPod : OK, so let's reach some conclusion.  Java JNI bindings seem to have a problem.  I volunteer to maintain bindings for Lua and potentially other languages, but unfortunately Java is not one of them.  I am happy to accomodate the maintenance if somebody wants to step up and fix it, though.  Any takers?  Otherwise, I think it is better to euthanize this code than keep it broken.

**Comment by pgc-13** [comment] 2019-05-17 10:29
@rmind @SingularityCat @simPod I think I solved the issue. We were using weak references which I think is a mistake/misunderstanding, since it allows the GC to nuke the referred object if there is no strong reference around. When inserting something into the LPM structure, that reference might well be the only one that exists (this is true for the test case) so it should not be weak. The nulls were most likely happening right after a GC run, which of course would appear a bit "random". I will submit a fix for this.

**Comment by pgc-13** [comment] 2019-05-17 10:49
@SingularityCat If you want to contribute your javac -h change that would be great as well :) Cheers

**Comment by simPod** [comment] 2019-05-17 11:40
Cool! Would be also handy to run java tests in travis but I have not yet found a way how to "cleanly" setup it for multi language. Probably Docker would be a way so I can look into it later.

**Comment by SingularityCat** [comment] 2019-05-17 13:32
It looks like `javac -h` is available in Java SE 9. If we want to support 8 or below, we'd need to support both methods.

Would it be preferable to support both?

**Comment by pgc-13** [comment] 2019-05-17 14:19
@SingularityCat Actually javac -h should be available in Java SE 8... however javah wasn't officially deprecated until SE 9 (I just tried javac -h in SE 7 vs 8. For SE 7, it says ```javac: invalid flag: -h```, but for SE 8 it says ```javac: -h requires an argument```.

**Comment by SingularityCat** [comment] 2019-05-17 15:00
Weird, it's not in the docs, but it looks like it's there...  ¯\\\_(ツ)\_/¯
If it works, I'll do a PR when I get home (assuming we don't care about SE 7).

**Comment by pgc-13** [comment] 2019-05-17 15:56
@SingularityCat I'm sure it's fine to require SE 8 for building this. If we really want SE 7 compatible build output, then I believe we can solve that with compatibility flags to javac (given that the java bindings themselves are 1.7 source compatible, which I think is the case) :)

**Comment by rmind** [comment] 2019-05-18 16:00
@moshisushi @SingularityCat : Excellent!  Thanks for working on this.

@simPod : [Travis](https://github.com/rmind/liblpm/blob/master/.travis.yml) already runs the C tests.  It should be a matter of adding the [Java environment](https://docs.travis-ci.com/user/languages/java/) and calling `cd liblpm/src/jni && make test` with the right `JAVA_HOME`.

**Comment by simPod** [comment] 2019-05-18 16:03
@rmind yup but AFAIK you can't have two environments in Travis, or am I mistaken?

**Comment by rmind** [comment] 2019-05-19 19:20
@simPod: I don't see any reason why, for example, OpenJDK couldn't be added as an additional package. But I will let you to figure that out. :)

I think we are done with this issue. Closing.

**Closed as completed by rmind** 2019-05-19 19:20 UTC

**Comment by simPod** [comment] 2022-05-02 19:51
@rmind see https://github.com/rmind/liblpm/pull/19 when you have a minute
